services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:4.13.4
    container_name: dtrack-apiserver
    environment:
      - ALPINE_DATABASE_MODE=internal
    volumes:
      - dtrack-data:/data
    ports:
      - "8083:8080"
    networks:
      - web
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:4.13.4
    container_name: dtrack-frontend
    environment:
      # - API_BASE_URL=http://localhost:8083
      - API_BASE_URL=https://dtrack-api.enblitz.com
    ports:
      - "8084:8080"
    networks:
      - web
    depends_on:
      - dtrack-apiserver
    restart: unless-stopped
volumes:
   dtrack-data:
networks:
  web:
    external: true
