services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:latest
    container_name: dtrack-apiserver
    environment:
      - ALPINE_DATABASE_MODE=internal
    volumes:
      - dtrack-data:/data
    ports:
      - "8083:8080"
    networks:
      - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dtrack-apiserver.rule=Host(`dtrack-apiserver.enblitz.com`)"
      - "traefik.http.routers.dtrack-apiserver.entrypoints=web"
      - "traefik.http.services.dtrack-apiserver.loadbalancer.server.port=8080"

  dtrack-frontend:
    image: dependencytrack/frontend:latest
    container_name: dtrack-frontend
    environment:
      - API_BASE_URL=http://dtrack-apiserver:8083
    ports:
      - "8084:8080"
    networks:
      - web
    depends_on:
      - dtrack-apiserver
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dtrack-frontend.rule=Host(`dtrack-frontend.enblitz.com`)"
      - "traefik.http.routers.dtrack-frontend.entrypoints=web"
      - "traefik.http.services.dtrack-frontend.loadbalancer.server.port=8080"
volumes:
   dtrack-data:
networks:
  web:
    external: true
