services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE="Asia/Singapore"
      - TZ="Asia/Singapore"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_SCHEMA=n8n
      - DB_POSTGRESDB_PASSWORD=dbn8npass
    networks:
      - web
      - db
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
volumes:
   n8n-data:
networks:
  web:
    external: true
  db:
    external: true
