global:
  scrape_interval: 15s  # Scrape targets every 15 seconds

scrape_configs:
  # Scrape config for Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Target for Node Exporter

  # Scrape config for prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Target for prometheus

  # Scrape config for cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
