---
services:
  grafana:
    image: grafana/grafana:11.2.0-ubuntu
    container_name: grafana
    networks:
      - web
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    # ports:
    #  - '3000:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.enblitz.com`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"


#volume
volumes:
  grafana-storage:

# Define networks
networks:
  web:
    external: true
