---
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    networks:
      - web
    # ports:
    #   - 8081:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.enblitz.com`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
# Define networks
networks:
  web:
    external: true
