---
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - web
    # ports:
    #   - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.enblitz.com`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  portainer_data:

# Define networks
networks:
  web:
    external: true
